homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 171.3
  unit_system: imperial
  time_zone: America/Chicago
  customize: !include includes/customize.yaml

zone:
  name: home
  latitude: !secret latitude
  longitude: !secret longitude
  icon: mdi:home
  radius: 300

zone 2:
  name: St. Lucas
  latitude: !secret school-latitude
  longitude: !secret school-longitude
  icon: mdi:school
  radius: 200

zone 3:
  name: Maryville
  latitude: !secret kschool-latitude
  longitude: !secret kschool-longitude
  icon: mdi:medical-bag
  radius: 500

zone 4:
  name: St. Catharine
  latitude: !secret school2-latitude
  longitude: !secret school2-longitude
  icon: mdi:school
  radius: 200

frontend:
updater:
history:
logbook:
discovery:
config:
http:
 api_password: !secret http_password
sun:

# 3rd party integrations

notify:
  - name: pushbullet
    platform: pushbullet
    api_key: !secret pushbullet_api_key

ifttt:
  key: !secret ifttt-api

tts:
  platform: google

sensor:
  - platform: darksky
    api_key: !secret darksky_api_key
    latitude: !secret latitude
    longitude: !secret longitude
    monitored_conditions:
      - temperature
      - temperature_max
      - temperature_min
      - humidity
      - precip_probability
      - cloud_cover
  - platform: template
    sensors:
      garage_door_status:
        friendly_name: 'Garage door'
        value_template: '{{ states.cover.garage_door_opener.state }}'


# hardware

ecobee:
  api_key: !secret ecobee-key

cover:
  - platform: myq
    username: !secret email
    password: !secret myq-password
    type: chamberlain

wemo:

switch:
  - platform: tplink
    host: 192.168.1.115

switch 2:
  - platform: tplink
    host: 192.168.1.119

switch 3:
  - platform: tplink
    host: 192.168.1.128

light:
  - platform: hue
    host: 192.168.1.105
  - platform: yeelight
    devices:
      192.168.1.137:
        name: Playroom
        transition: 1000

zwave:
  usb_path: /dev/ttyACM0

emulated_hue:
  type: alexa
  host_ip: 192.168.1.147
  expose_by_default: false

alarm_control_panel:
  platform: simplisafe
  username: !secret simplisafe_username
  password: !secret simplisafe_password

apple_tv:
  - name: Apple TV
    host: 192.168.1.129
    login_id: !secret apple_tv_login_id

camera:
  - platform: amcrest
  
amcrest:
  - host: 192.168.1.124
    username: admin
    password: !secret amcrest_password
  - host: 192.168.1.102
    username: admin
    password: !secret amcrest_password

# amcrest:
#  - host: 192.168.1.125
#    username: admin
#    password: !secret amcrest_password
#  - host: 192.168.1.102
#    username: admin
#    password: !secret amcrest_password


#includes

automation: !include includes/automations.yaml
group: !include includes/groups.yaml
scene: !include includes/scenes.yaml

#scripts -- move this to a file later

script:
  flash_lights:
    alias: Flash Lights
    sequence:
      - service: homeassistant.turn_on
        data:
          entity_id:
            - light.living_ceiling_level
            - switch.wemo_switch
            - light.the_lamp
            - light.cafe_level
            - light.island_level_11_0
            - light.kitchen_ceiling_level
            - light.dining_level
            - light.hallway1_level
            - light.hallway2_level
            - switch.kitchen_under_ca_switch
            - switch.porch_switch
            - switch.coach_switch
      - delay:
          seconds: 1
      - service: homeassistant.turn_off
        data:
          entity_id:
            - light.living_ceiling_level
            - switch.wemo_switch
            - light.the_lamp
            - light.cafe_level
            - light.island_level_11_0
            - light.kitchen_ceiling_level
            - light.dining_level
            - light.hallway1_level
            - light.hallway2_level
            - switch.kitchen_under_ca_switch
            - switch.porch_switch
            - switch.coach_switch
      - service: script.turn_on
        data:
          entity_id: script.light_loop
  light_loop:
    alias: Light flash loop
    sequence:
      - delay:
          seconds: 1
      - service: script.turn_on
        data:
          entity_id: script.flash_lights
  light_loop_kill:
    alias: Kill flashing lights
    sequence:
      service: script.turn_off
      data:
        entity_id: script.light_loop

input_boolean:
  vacation_mode:
    initial: off
